export const FRAGRANCES = [
  {
    id: 1,
    name: "Ambré Étoile",
    family: "Oriental",
    badge: "Best Seller",
    notes: "Vanilla · Amber · Sandalwood · Musk",
    price: 1850000,
    img: "./assets/scents/AmbréÉtoile.jpg",
  },
  {
    id: 2,
    name: "Azure Mist",
    family: "Aquatic",
    badge: "New",
    notes: "Sea Salt · Bergamot · White Cedar · Vetiver",
    price: 1650000,
    img: "./assets/scents/Azure Mist.jpg",
  },
  {
    id: 3,
    name: "Noir Spice",
    family: "Woody Spicy",
    badge: "",
    notes: "Black Pepper · Oud · Leather · Tobacco",
    price: 1950000,
    img: "./assets/scents/Noir Spice.jpg",
  },
  {
    id: 4,
    name: "Jardin Rose",
    family: "Floral",
    badge: "",
    notes: "Rose · Peony · Jasmine · Light Musk",
    price: 1750000,
    img: "./assets/scents/Jardin Rose.jpg",
  },
  {
    id: 5,
    name: "Citrus Soleil",
    family: "Citrus",
    badge: "",
    notes: "Grapefruit · Lemon · Neroli · Oakmoss",
    price: 1550000,
    img: "./assets/scents/Citrus Soleil.jpg",
  },
  {
    id: 6,
    name: "Velvet Oud",
    family: "Oriental",
    badge: "Limited",
    notes: "Oud · Rose · Saffron · Benzoin",
    price: 2250000,
    img: "./assets/scents/Velvet Oud.jpg",
  },
  {
    id: 7,
    name: "YSL Y EDP",
    family: "Woody Aromatic",
    badge: "Limited",
    notes: "Apple · Bergamot · Ginger · Sage",
    price: 22500000,
    img: "./assets/scents/YSL Y EDP.jpg",
  },
  {
    id: 8,
    name: "Montblanc",
    family: "Amber Spicy",
    badge: "Limited",
    notes: "Apple · Bergamot · Ginger · Sage",
    price: 1100000,
    img: "./assets/scents/Montblanc.jpg",
  },
  {
    id: 9,
    name: "Rasasi Virtue",
    family: "Oriental Woody",
    badge: "Limited",
    notes: "Oud · Rose · Saffron · Benzoin",
    price: 2250000,
    img: "./assets/scents/Rasasi Virtue.jpg",
  },
  {
    id: 10,
    name: "Dior Sauvage",
    family: "Aromatic Fougère",
    badge: "Limited",
    notes: "Calabrian Bergamot · Lavender",
    price: 4250000,
    img: "./assets/scents/Dior Sauvage.jpg",
  },
];